import { BeatTrack, LeaseOption } from '../models/Beat';

const beatTracksDataMock: BeatTrack[] = [
  {
    id: 'midnight-drive',
    slug: 'midnight-drive',
    title: 'Midnight Drive',
    artist: '8ZEE MUSIC',
    description: 'Warm synth layers and a steady pulse for confident, late-night energy.',
    genre: 'Lo-fi / Trap',
    bpm: 92,
    key: 'F minor',
    tags: [],
    durationSeconds: 18,
    previewFrequency: 110,
    coverGradient: 'linear-gradient(135deg, #1d3a2d 0%, #0f1b13 100%)',
  },
  {
    id: 'city-lights',
    slug: 'city-lights',
    title: 'City Lights',
    artist: '8ZEE MUSIC',
    description: 'A brighter, more percussive loop with movement for modern visuals and promos.',
    genre: 'Trap / Pop',
    bpm: 104,
    key: 'A minor',
    tags: [],
    durationSeconds: 18,
    previewFrequency: 130,
    coverGradient: 'linear-gradient(135deg, #254c3a 0%, #122118 100%)',
  },
  {
    id: 'after-hours',
    slug: 'after-hours',
    title: 'After Hours',
    artist: '8ZEE MUSIC',
    description: 'Deep low-end, spacious rhythm, and a clean loop suited for vocal toplines.',
    genre: 'R&B / Trap',
    bpm: 84,
    key: 'D minor',
    tags: [],
    durationSeconds: 18,
    previewFrequency: 147,
    coverGradient: 'linear-gradient(135deg, #163326 0%, #0b140f 100%)',
  },
];

const leaseOptionsDataMock: LeaseOption[] = [
  {
    id: 'basic',
    name: 'Basic Lease',
    price: '$29.99',
    includedFiles: ['MP3 download'],
    rights: [
      'Non-exclusive license',
      'Up to 10,000 streams',
      'Use for one song or project',
      'Credit must be given to the producer',
    ],
    limitations: ['No WAV file included'],
    ctaLabel: 'Select Basic Lease',
    type: 'lease',
  },
  {
    id: 'premium',
    name: 'Premium Lease',
    price: '$49.99',
    includedFiles: ['MP3 download', 'WAV download'],
    rights: [
      'Non-exclusive license',
      'Up to 50,000 streams',
      'Use for one song or project',
      'Monetization allowed on major platforms',
      'Credit must be given to the producer',
    ],
    limitations: ['No stems included'],
    recommended: true,
    ctaLabel: 'Select Premium Lease',
    type: 'lease',
  },
  {
    id: 'unlimited',
    name: 'Unlimited Lease',
    price: '$99.99',
    includedFiles: ['MP3 download', 'WAV download', 'Track stems'],
    rights: [
      'Non-exclusive license',
      'Unlimited streams',
      'Monetization allowed',
      'Live performances allowed',
      'Use for one song or project',
      'Credit must be given to the producer',
    ],
    limitations: [],
    ctaLabel: 'Select Unlimited Lease',
    type: 'lease',
  },
  {
    id: 'exclusive',
    name: 'Exclusive Rights',
    price: 'Custom / Contact for price',
    includedFiles: ['MP3 download', 'WAV download', 'Track stems'],
    rights: [
      'Buyer receives exclusive ownership rights',
      'Beat is removed from public sale after purchase',
      'Unlimited streams and monetization',
      'Full commercial usage rights',
    ],
    limitations: ['Requires direct inquiry before checkout'],
    ctaLabel: 'Contact for Exclusive Rights',
    type: 'exclusive',
  },
];

export const getBeatsInformation = (): BeatTrack[] => beatTracksDataMock;
export const getLeaseOptionsInformation = (): LeaseOption[] => leaseOptionsDataMock;
